#!/command/with-contenv bash

if [ -n "${ACCESS_LOG}" ]; then
  echo "Set access logging to ${ACCESS_LOG}"
else
  ACCESS_LOG=/dev/stdout
fi

sed -i -e "s@^\(\s*access_log\s\s*\).*;@\1${ACCESS_LOG};@" /etc/nginx/conf.d/default.conf

